path_save_to: './SI_Toolkit_ASF/Experiments/DG1/Recordings/Train/'  # Where to save experiment recording per default
#path_save_to: './Experiment_Recordings/'
seed:    # If not assign random seed based on datetime is used
split: [0.8, 0.1]  # Train/Val/(Test) split - only matters if you run it in ML Pipeline mode
initial_states:
  from_file:
    load_from_file: false
    features: ['pose_x', 'pose_y']
    file_with_initial_states: './ExperimentRecordings/F1TENTH_Blank-MPPI-0__2022-11-29_10-19-19.csv'
  random:
    # Unassigned variables will be randomly initialized (see below)
    position:
    positionD:
    angle:
    angleD:
    target_position:
    init_limits: # The initial state is randomly chosen from below range if above is not assigned
      angle: [90.0, 180.0]  # degree, 0 is up, 180 down, set the range for right half plane, same will be applied to left
      angleD: 40.0
      position: 0.5  # Fraction of TrackHalfLength to each side
      positionD: 0.01 # Fraction of TrackHalfLength to each side

dt: 0.03
number_of_initial_states: 1000
number_of_trajectories_per_initial_state: 1
trajectory_length: 100
#  number_of_experiments = number_of_initial_states * number_of_trajectories_per_initial_state # How many experiments will be generated
#  experiment_length = trajectory_length * dt
save:
  singlefile: true
control_inputs:
  strategy: 'random input'  # Also possible 'constant input'

