#path_save_to: './xxx/'  # Where to save experiment recording per default
path_save_to: './ExperimentRecordings/'
seed:    # If not assign random seed based on datetime is used
split: [0.8, 0.1]  # Train/Val/(Test) split - only matters if you run it in ML Pipeline mode
initial_states:
  from_file:
    load_from_file: false
    features: ['pose_x', 'pose_y']
    file_with_initial_states: './ExperimentRecordings/F1TENTH_Blank-MPPI-0__2022-11-29_10-19-19.csv'
  random:
    # Unassigned variables will be randomly initialized (see below)
    yaw_rate: 
    velocity_x: 0
    yaw_angle:
    x:
    y:
    slip_angle:
    steering_angle:
    init_limits: # The initial state is randomly chosen from below range if above is not assigned
      yaw_rate: [0.0, 3.25] #[0.0, 3.25]
      velocity_x: [-2.0, 20.0] #[-2.0, 20.0]
      yaw_angle: [-3.1415, 3.1415] #[-3.1415, 3.1415]
      x: [-50, 50] #[-50, 50]
      y: [-50, 50] #[-50, 50]
      slip_angle: [-2.0, 2.0] #[-2.0, 2.0]
      steering_angle: [-0.5, 0.5] #[-0.5, 0.5]
dt: 0.03
number_of_initial_states: 500
number_of_trajectories_per_initial_state: 1
trajectory_length: 500
save:
  singlefile: true
control_inputs:
  # Set usage of PID in utilities/Settings.py
  strategy: 'constant'  # random/constant

  # With PID:
  angular_control_range: [0.0, 0.2] # [mu, sigma]
  translational_control_range: [0, 20.0]

  # Without PID:
  # angular_control_range: [0.0, 1.1] # [mu, sigma]
  # translational_control_range: [-9, 9]

