# path_save_to: './ExperimentRecordings/'
path_save_to: './SI_Toolkit_ASF/Experiments/0_tryout/Recording'  # Not considered when running in ML pipeline. Then a new experiment is created in SI_Toolkit_ASF
seed:    # If not assign random seed based on datetime is used
split: [0.8, 0.1]  # Train/Val/(Test) split - only matters if you run it in ML Pipeline mode
initial_states:
  from_file:
    load_from_file: false
    features: ['pose_x', 'pose_y']
    file_with_initial_states: './ExperimentRecordings/F1TENTH_Blank-MPPI-0__2022-11-29_10-19-19.csv'
  random:
    # Unassigned variables will be randomly initialized (see below)
    yaw_rate: 0
    velocity_x: 5
    yaw_angle: 0
    x:
    y:
    slip_angle: 0
    steering_angle: 0
    init_limits: # The initial state is randomly chosen from below range if above is not assigned
      yaw_rate: [-4.0, 4.0] #[0.0, 3.25]
      velocity_x: [0, 10.0] #[-2.0, 20.0]
      yaw_angle: [-3.1415, 3.1415] #[-3.1415, 3.1415]
      x: [-50, 50] #[-50, 50]
      y: [-50, 50] #[-50, 50]
      slip_angle: [-0.3, 0.3] #[-2.0, 2.0]
      steering_angle: [-0.4189, 0.4189] #[-0.5, 0.5]
dt: 0.04
number_of_initial_states: 40
number_of_trajectories_per_initial_state: 1
trajectory_length: 7500
save_single_file: false
control_inputs:
  steering:
    # Set usage of PID in utilities/Settings.py
    strategy: 'mixed'  # random/constant/mixed
    generate_around_state: false  # Set the inputs to be around the current state
    hold_constant_input: 6  # For mixed strategy, how long to hold a constant input
    distribution: 'normal' # uniform/normal
    control_range: [0.0, 0.20] # [mu, sigma]

    # With PID:
  velocity:
    strategy: 'mixed'
    generate_around_state: false
    hold_constant_input: 10
    distribution: 'uniform'
    control_range: [1.0, 8.0]