# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 6

# map paths
map_path: 'MultiAgents/maps/Oschersleben'
map_ext: '.png'

# starting pose for map
starting_positions: 
 - [0.0702245, 0.3002981, 2.79787]
 - [0.9966514, -0.9306893, 2.79787]
 - [-1., 4., 1.37079632679]
 - [-1.5, 6., 1.37079632679]
  

# raceline path and indices
wpt_path: 'MultiAgents/maps/Oschersleben_waypoints.csv'
wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5

# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345