planner:
  #  CLIP_CONTROL_INPUT: [ 22, 1.2 ]            # How to clip control input, symmetric: use with PID
  CLIP_CONTROL_INPUT: [ 7, 3.5 ]            # How to clip control input, symmetric: use without PID
  LOOK_AHEAD_WAYPOINTS: 15
  INTERPOLATE_WAYPOINTS: 4