planner:
  #  CLIP_CONTROL_INPUT: [ 22, 1.2 ]            # How to clip control input, symmetric: use with PID
  CLIP_CONTROL_INPUT: [ 9.3, 3.5 ]            # How to clip control input, symmetric: use without PID

waypoints:
  LOOK_AHEAD_STEPS: 13                    # Number of original waypoints that are considered for cost
  INTERPOLATION_STEPS: 1                  # >= 1 Interpolation steps to increase waypoint resolution 
  DECREASE_RESOLUTION_FACTOR: 2           # >= 1 Only take every n^th waypoint to decrease resolution
  IGNORE_STEPS: 2                         # Number of interpolated waypoints to ignore starting at the closest one