planner:
  #CLIP_CONTROL_INPUT: [ 1.02, 20 ]         # How to clip control input, symmetric: use with PID
  CLIP_CONTROL_INPUT: [3.2, 9.5 ]            # How to clip control input, symmetric: use without PID [angular_control, translational_control]

waypoints:
  LOOK_AHEAD_STEPS: 25                    # Number of original waypoints that are considered for cost
  INTERPOLATION_STEPS: 1                  # >= 1 Interpolation steps to increase waypoint resolution
  DECREASE_RESOLUTION_FACTOR: 1           # >= 1 Only take every n^th waypoint to decrease resolution
  IGNORE_STEPS: 3                        # Number of interpolated waypoints to ignore starting at the closest one