planner:
  #  CLIP_CONTROL_INPUT: [ 22, 1.2 ]            # How to clip control input, symmetric: use with PID
  CLIP_CONTROL_INPUT: [ 9.3, 3.5 ]            # How to clip control input, symmetric: use without PID

waypoints:
  LOOK_AHEAD_STEPS: 10                     # Number of original waypoints that are considered for cost -> this nr of wypts is saved in CSV #10 exampleMap
  INTERPOLATION_STEPS: 2                  # >= 1 Interpolation steps to increase waypoint resolution
  IGNORE_STEPS: 15                       # Number of interpolated waypoints to ignore starting at the closest one   #15 exampleMap