
MAX_COST = 10000

DRAW_LIVE_ROLLOUTS = False

# Initializing parameters
NUMBER_OF_INITIAL_TRAJECTORIES = 100
INITIAL_STEERING_VARIANCE = 3
INITIAL_ACCELERATION_MEAN = 0
INITIAL_ACCELERATION_VARIANCE = 2


# Parameters for rollout
NUMBER_OF_TRAJECTORIES = 100
STEP_STEERING_VARIANCE = 1
STEP_ACCELERATION_VARIANCE =5

NUMBER_OF_STEPS_PER_TRAJECTORY = 15
INVERSE_TEMP = 0.1


NUMBER_OF_IGNORED_CLOSEST_WAYPOINTS = 2
NUMBER_OF_NEXT_WAYPOINTS = 15