from utilities.Settings import Settings
from utilities.state_utilities import *

import os.path
import numpy as np
import pandas as pd
import yaml

'''
HOW TO USE:

1. Generate/Get a Waypoints CSV File (https://github.com/TUMFTM/global_racetrajectory_optimization )
2. Set the MAP_WAYPOINT_FILE in Settings.py to the generated file (without .csv)
3. Set Waypoint parameters in config.yml
4. Use inside planner class like this:

# Import 
from utilities.waypoint_utils import WaypointUtils

# Initialize
waypoint_utils = WaypointUtils()

# Update at every step for the next_waypoints with the current car's position
car_position = [0., 0.]
waypoint_utils.update_next_waypoints(car_position)

# Access next waypoint's positions list([x,y]):
waypoints_positions = waypoint_utils.next_waypoint_positions

# Or Access next full waypoints list([dist, x, y, abs_angle, rel_angle, v_x, acc_x]):
waypoints = waypoint_utils.next_waypoints

'''
     
class WaypointUtils:
    
    def __init__(self, waypoint_file = None):
        config = yaml.load(open("config.yml", "r"), Loader=yaml.FullLoader)
        
        self.interpolation_steps = config['waypoints']['INTERPOLATION_STEPS']
        self.look_ahead_steps = self.interpolation_steps * config['waypoints']['LOOK_AHEAD_STEPS']
        self.ignore_steps = config['waypoints']['IGNORE_STEPS']
        
        # Waypoints generated by https://github.com/TUMFTM/global_racetrajectory_optimization   
        self.original_waypoints = WaypointUtils.load_waypoints(waypoint_file)
        
        # Full waypoints [traveled_dist, x, y, abs_angle, rel_angle, vel_x, acc_x]
        self.waypoints = WaypointUtils.get_interpolated_waypoints(self.original_waypoints, self.interpolation_steps)
        self.waypoint_positions = WaypointUtils.get_waypoint_positions(self.waypoints)
        
        self.trajectory_vectors, self.trajectory_norms, self.directions = self.get_vectors_between_waypoint_positions()
        self.nearest_waypoint_index = None
        
        # next waypoints including the ones ignored by index offset: Relevant for looking for next (cache for looking for next one)
        self.current_waypoint_cache = np.zeros((self.look_ahead_steps, 7), dtype=np.float32) 
        
         # next waypoints considering ignored waypoints index offset
        self.next_waypoints = np.zeros((self.look_ahead_steps, 7), dtype=np.float32)
        self.next_waypoint_positions = np.zeros((self.look_ahead_steps,2), dtype=np.float32)
        
        if(self.waypoints is None):
            self.current_waypoint_cache = np.array([])
            self.next_waypoints = np.array([])
            self.next_waypoint_positions = np.array([])
        
        
        
    def update_next_waypoints(self, car_position):
        if self.waypoints is None: return
        if self.nearest_waypoint_index is None:
            # Run initial search of starting waypoint (all waypoints)
            nearest_waypoint_index = WaypointUtils.get_nearest_waypoint_index(car_position, self.waypoints)  
        else: # only look for next waypoint in the current waypoint cache
            nearest_waypoint_index = self.nearest_waypoint_index + WaypointUtils.get_nearest_waypoint_index(car_position, self.current_waypoint_cache)

        next_waypoints_including_ignored = []
        for j in range(self.look_ahead_steps + self.ignore_steps):
            next_waypoint = self.waypoints[(nearest_waypoint_index + j) % len(self.waypoints)]
            next_waypoints_including_ignored.append(next_waypoint)
        next_waypoints_including_ignored = np.array(next_waypoints_including_ignored)
        
        self.next_waypoints = next_waypoints_including_ignored[self.ignore_steps:]
        self.current_waypoint_cache = next_waypoints_including_ignored
        
        self.next_waypoint_positions = WaypointUtils.get_waypoint_positions(self.next_waypoints)
        self.nearest_waypoint_index = nearest_waypoint_index
        
    @staticmethod
    def load_waypoints(map_waypoint_file = None):
        
        path = Settings.MAP_WAYPOINT_FILE
        if map_waypoint_file is not None:
            path = map_waypoint_file
        
        if path is None:
            return None
            
        file_path = path + '.csv'
        assert os.path.isfile(file_path), "Waypoint file (" + path+  ") does not exist"
        
        waypoints = pd.read_csv(file_path, header=None).to_numpy()
        return np.array(waypoints)
     
    @staticmethod
    def get_interpolated_waypoints(waypoints, interpolation_steps):
        if waypoints is None: return None
        assert(interpolation_steps >= 1)
        waypoints_interpolated = []
        
        for j in range(len(waypoints) - 1):
            for i in range(interpolation_steps):
                interpolated_waypoint = waypoints[j] + (float(i)/interpolation_steps)*(waypoints[j+1]-waypoints[j])
                waypoints_interpolated.append(interpolated_waypoint)
        waypoints_interpolated.append(waypoints[-1])
        return waypoints_interpolated
    
    @staticmethod
    def get_nearest_waypoint_index(car_position, waypoints):

        min_dist = 10000
        min_dist_index = 0

        def squared_distance(p1, p2):
            squared_distance = abs(p1[0] - p2[0]) ** 2 + abs(p1[1] - p2[1]) ** 2
            return squared_distance

        waypoint_positions = WaypointUtils.get_waypoint_positions(waypoints)
        for i in range(len(waypoint_positions)):
            dist = squared_distance(waypoint_positions[i], car_position)
            if (dist) < min_dist:
                min_dist = dist
                min_dist_index = i

        return min_dist_index
    
    @staticmethod
    def get_waypoint_positions(waypoints):
        if waypoints is None: return None
        return waypoints[:, 1:3]
    
    def get_vectors_between_waypoint_positions(self):
        if self.waypoints is None: return None, None, None
        waypoint_positions = self.get_waypoint_positions(self.waypoints)
        vectors = []
        norms = []
        directions = []
        for i in range(len(waypoint_positions)-1):
            vector = waypoint_positions[i + 1] - waypoint_positions[i]
            vectors.append(vector)
            norm = np.linalg.norm(vector)
            norms.append(norm)
            directions.append(vector/norm)
        return vectors, norms, directions