from setuptools import setup, find_packages

setup(
    name='f110_sim',
    version='0.3.0',
    description='F1TENTH Simulation Environment',
    author='Hongrui Zheng, Marcin Paluch, Florian Bolli',
    author_email='billyzheng.bz@gmail.com',
    url='https://f1tenth.org',
    packages=find_packages(),
    install_requires=[
        'numpy==1.24.3',
        'Pillow',
        'scipy',
        'psutil',
        'numba',
        'pyyaml',
        'pyglet==1.5.26',
        'pyopengl',
        'matplotlib',
        'tqdm',
        'scikit-image',
        'ruamel.yaml',
        'pyserial',
        'trajectory_planning_helpers==0.76',
        'casadi',
        'pynput',
        'gitpython',
        'pandas',
        'shapely',
        'gymnasium',
        'stable_baselines3',
        'tensorboard==2.14',
        'seaborn',
        'pytest',
        'opencv-python',
        'tensorboardX',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
    ],
    python_requires='>=3.7',
)
