mpc:
  calculate_optimal_trajectory: true
  computation_library: tensorflow
  controller_logging: false
  cost_function_specification: racing
  optimizer: mppi
  predictor_specification: ODE_TF
neural-imitator-pytorch:
  PATH_TO_MODELS: ./Control_Toolkit_ASF/Controllers/models_for_neural_imitator_tf/
  controller_logging: true
  mpc_horizon: 40
  net_name: GRU-6IN-32H1-32H2-1OUT-0
  num_rollouts: 1
  seed: null
neural-imitator-tf:
  PATH_TO_MODELS: ./Control_Toolkit_ASF/Controllers/models_for_neural_imitator_tf/
  controller_logging: true
  mpc_horizon: 40
  net_name: GRU-6IN-32H1-32H2-1OUT-4
  num_rollouts: 1
  seed: null
