mpc:
  optimizer: 'rpgd-tf' # 'mppi' or 'rpgd-tf'
#  optimizer: 'rpgd-tf' # 'mppi' or 'rpgd-tf'
  predictor_specification: ODE_TF    # Dense-8IN-128H1-128H2-6OUT-43 Can be "ODE", "ODE_TF", network/GP name (possibly with path) e.g. 'GRU-6IN-32H1-32H2-5OUT-0'/'SGP_30' or a name of a custom predictor. For more info see config_predictors in SI_Toolkit_ASF

  cost_function_specification: 'racing'  # One of "default", "quadratic_boundary_grad", "quadratic_boundary_nonconvex", "quadratic_boundary"
  computation_library: tensorflow  # One of "numpy", "tensorflow", "pytorch". Defaults to "numpy" if none given.
  controller_logging: false
  calculate_optimal_trajectory: true
neural-imitator:
  seed: null                            # If null, random seed based on datetime is used
  PATH_TO_MODELS: './SI_Toolkit_ASF/Experiments/flo-dataset/Models/'
  net_name: 'GRU-63IN-32H1-32H2-2OUT-3'  # TF
  controller_logging: True
  computation_library: tensorflow
  input_at_input: true  # If true the network input is provided to step function, if not, system state is provided and controller tries to get the remaining inputs from environment parameters
  hls4ml: true
stanley:
  controller_logging: False
  computation_library: numpy
fpga:
  seed: null                            # If null, random seed based on datetime is used
  PATH_TO_MODELS: './SI_Toolkit_ASF/Experiments/'
  net_name: 'Dense-47IN-16H1-16H2-2OUT-1'  # TF
#  net_name: 'GRU-6IN-32H1-32H2-1OUT-0'  # Pytorch
  input_at_input: true
  controller_logging: True
  SERIAL_PORT: 1
  SERIAL_BAUD: 115200
