Car:
  following_target: null
  racing:
    R: 1.0
    acceleration_cost_weight: 0.0
    angular_velocity_cost_weight: 0.001
    cc_weight: 0.0
    ccrc_weight: 1.0
    desired_max_speed: 3.8
    distance_to_waypoints_cost_weight: 10.0
    max_acceleration: 9.2
    mppi: null
    rpgd-tf: null
    speed_control_diff_to_waypoints_cost_weight: 1.0
    steering_cost_weight: 0.0
    target_distance_cost_weight: 0.0
    terminal_speed_cost_weight: 0.0
    velocity_diff_to_waypoints_cost_weight: 0.0
    waypoint_velocity_factor: 0.15
    'waypoint_velocity_factor ': 0.15
cost_function_name_default: racing
