mpc:
  optimizer: "rpgd" # 'mppi' or 'rpgd'
  # optimizer: "mppi" # 'mppi' or 'rpgd'
  # predictor_specification: neural_flo    # Dense-8IN-128H1-128H2-6OUT-43 Can be "ODE", "ODE_TF", network/GP name (possibly with path) e.g. 'GRU-6IN-32H1-32H2-5OUT-0'/'SGP_30' or a name of a custom predictor. For more info see config_predictors in SI_Toolkit_ASF
  # predictor_specification: neural_parameter_determination    # Dense-8IN-128H1-128H2-6OUT-43 Can be "ODE", "ODE_TF", network/GP name (possibly with path) e.g. 'GRU-6IN-32H1-32H2-5OUT-0'/'SGP_30' or a name of a custom predictor. For more info see config_predictors in SI_Toolkit_ASF
  predictor_specification: ODE # Dense-8IN-128H1-128H2-6OUT-43 Can be "ODE", "ODE_TF", network/GP name (possibly with path) e.g. 'GRU-6IN-32H1-32H2-5OUT-0'/'SGP_30' or a name of a custom predictor. For more info see config_predictors in SI_Toolkit_ASF

  cost_function_specification: "racing" # One of "default", "quadratic_boundary_grad", "quadratic_boundary_nonconvex", "quadratic_boundary"
  computation_library: tensorflow # One of "numpy", "tensorflow", "pytorch". Defaults to "numpy" if none given.
  controller_logging: false
  calculate_optimal_trajectory: true
  device: "/device:CPU:0"

neural-imitator:
  seed: null # If null, random seed based on datetime is used
  PATH_TO_MODELS: "./SI_Toolkit_ASF/Experiments/04_08_RCA1_noise/Models/"
  net_name: "GRU-94IN-128H1-128H2-128H3-2OUT-0" # TF

  input_at_input: True
  input_precision: "float" #'ap_fixed<20,6>'   # Can be 'float' - currently do nothing, or 'ap_fixed<total number of bits, integer bits + 1 sign bit>' - adjusting the number precision of the input
  controller_logging: True
  hls4ml: false
stanley:
  controller_logging: False
  computation_library: numpy
fpga:
  seed: null                            # If null, random seed based on datetime is used
  PATH_TO_MODELS: './AnalyseData/iros24/IROS24_models/'
  net_name: 'Dense-64IN-64H1-64H2-2OUT-0-0'  # TF
  #  net_name: 'GRU-6IN-32H1-32H2-1OUT-0'  # Pytorch
  input_at_input: true
  controller_logging: True
  SERIAL_PORT: 1
  SERIAL_BAUD: 230400
