cost_function_name_default: racing
# Default value is used if controller does not specify a cost_function_specification (leave empty)
# Cost functions are grouped by environment name in a folder within Control_Toolkit_ASF.Cost_Functions
# Check config.yml to learn more on how cost_functions are selected

Car:
  racing:

    cc_weight: 0.0                        # control cost; for mppi, to concord with theory, check that cc, ccrc and R are the same as in config_optimizers.yml
    ccrc_weight: [5.0, 0.0]               # Steering and throttle; penalty of instant control change
    ccocrc_weight: [0.0, 0.0]             # Steering and throttle; penalizing |∆u(t)-∆u(t-1)|
    icdc_weight: [0.0, 0.0]               # Steering and throttle; special penalty to discourage change at the very first control input


    crash_cost_safe_margin: 0.4
    crash_cost_max_cost: 100.0
    crash_cost_slope: 30.0

    R: 1.0                                # How much to punish Q, For MPPI YOU have to make sure that this is the same as in optimizer config, as it plays a special role in the optimization algorithm as well as is used in cost functions!
    distance_to_waypoints_cost_weight: 20.0
    velocity_diff_to_waypoints_cost_weight: 0.0
    angular_velocity_cost_weight: 0.01
    angle_difference_to_wp_cost_weight: 1.
    speed_control_diff_to_waypoints_cost_weight: 30.0  # Penalize difference between desired speed of control and the position's closest waypoint
    
    slipping_cost_weight: 0.01
    steering_cost_weight: 0.0
    terminal_speed_cost_weight: 0.0
    target_distance_cost_weight: 0.0            #only if you want to follow a target on an empty map
    waypoint_velocity_factor : 1.0 # Dont touch... adjust in maps/speed_scalling.yaml
    acceleration_cost_weight: 0.0
    max_acceleration: 9.2
    desired_max_speed: 3.8             # desired max speed for the car [m/s]

    # Different optimizers works the best with different cost functions parameters
    mppi:

    rpgd-tf:


  following_target:
    # TODO: The parameters not set yet, same as for racing