cem-gmm-tf:
  cem_best_k: 40
  cem_initial_action_stdev: 0.5
  cem_outer_it: 3
  cem_stdev_min: 0.01
  mpc_horizon: 40
  num_rollouts: 200
  seed: null
cem-grad-bharadhwaj-tf:
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-08
  cem_best_k: 8
  cem_initial_action_stdev: 2
  cem_outer_it: 2
  cem_stdev_min: 1.0e-06
  gradmax_clip: 5
  learning_rate: 0.05
  mpc_horizon: 50
  num_rollouts: 32
  seed: null
  warmup: false
  warmup_iterations: 250
cem-naive-grad-tf:
  cem_best_k: 40
  cem_initial_action_stdev: 0.5
  cem_outer_it: 1
  cem_stdev_min: 0.1
  gradmax_clip: 10
  learning_rate: 0.1
  mpc_horizon: 35
  num_rollouts: 200
  seed: null
cem-tf:
  cem_best_k: 40
  cem_initial_action_stdev: 0.5
  cem_outer_it: 3
  cem_stdev_min: 0.01
  mpc_horizon: 40
  num_rollouts: 200
  seed: null
  warmup: false
  warmup_iterations: 250
gradient-tf:
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-07
  gradient_steps: 5
  gradmax_clip: 5
  initial_action_stdev: 0.5
  learning_rate: 0.05
  mpc_horizon: 35
  num_rollouts: 40
  rtol: 0.001
  seed: null
  warmup: false
  warmup_iterations: 250
mppi:
  LBD: 0.01
  NU: 2000.0
  R: 1.0
  SQRTRHOINV:
  - 0.05
  - 0.05
  cc_weight: 0.0
  mpc_horizon: 10
  num_rollouts: 9000
  period_interpolation_inducing_points: 1
  seed: null
mppi-optimize-tf:
  LBD: 100.0
  NU: 1000.0
  R: 1.0
  SQRTRHOINV: 0.02
  adam_beta_1: 0.4
  adam_beta_2: 0.8
  adam_epsilon: 1.0e-07
  cc_weight: 1.0
  gradmax_clip: 1000
  mpc_horizon: 35
  mppi_LR: 0.02
  num_rollouts: 400
  optim_steps: 10
  period_interpolation_inducing_points: 10
  seed: null
mppi-var-tf:
  LBD_mc: 10.0
  LR: 1000
  NU_mc: 20.0
  R: 1.0
  SQRTRHOINV_mc: 0.002
  STDEV_max: 10
  STDEV_min: 0.01
  cc_weight: 1.0
  max_grad_norm: 100000
  mpc_horizon: 35
  num_rollouts: 400
  period_interpolation_inducing_points: 10
  seed: null
random-action-tf:
  mpc_horizon: 35
  num_rollouts: 320
  seed: null
rpgd-me-param-tf:
  SAMPLING_DISTRIBUTION: uniform
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-08
  gradmax_clip: 10
  learning_rate: 0.01
  maximum_entropy_alpha: 0.0
  mpc_horizon: 40
  num_rollouts: 32
  opt_keep_k_ratio: 0.25
  outer_its: 25
  period_interpolation_inducing_points: 1
  resamp_per: 1
  rtol: 0.001
  sample_stdev: 0.5
  seed: null
  warmup: false
  warmup_iterations: 250
rpgd-me-tf:
  SAMPLING_DISTRIBUTION: uniform
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-08
  gradmax_clip: 10
  learning_rate: 0.01
  maximum_entropy_alpha: 0.0
  mpc_horizon: 40
  num_rollouts: 32
  opt_keep_k_ratio: 0.25
  outer_its: 25
  period_interpolation_inducing_points: 1
  resamp_per: 1
  rtol: 0.001
  sample_stdev: 0.5
  seed: null
  warmup: false
  warmup_iterations: 250
rpgd-ml-tf:
  SAMPLING_DISTRIBUTION: uniform
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-08
  gradmax_clip: 10
  learning_rate: 0.01
  maximum_entropy_alpha: 0.1
  mpc_horizon: 40
  num_rollouts: 32
  opt_keep_k_ratio: 0.25
  outer_its: 5
  period_interpolation_inducing_points: 1
  resamp_per: 1
  rtol: 0.001
  sample_stdev: 0.5
  seed: null
  warmup: false
  warmup_iterations: 250
rpgd-particle-tf:
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-08
  gradmax_clip: 10
  learning_rate: 0.01
  mpc_horizon: 40
  num_rollouts: 32
  opt_keep_k_ratio: 0.25
  outer_its: 5
  period_interpolation_inducing_points: 1
  resamp_per: 1
  rtol: 0.001
  sample_stdev: 0.5
  seed: null
  warmup: false
  warmup_iterations: 250
rpgd-tf:
  SAMPLING_DISTRIBUTION: uniform
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-08
  gradmax_clip: 5
  learning_rate: 0.1
  mpc_horizon: 10
  num_rollouts: 32
  opt_keep_k_ratio: 0.75
  outer_its: 4
  period_interpolation_inducing_points: 2
  resamp_per: 5
  rtol: 0.001
  sample_mean:
  - 0.0
  - 3.8
  sample_stdev:
  - 0.3
  - 0.3
  sample_whole_control_space: false
  seed: null
  uniform_dist_max:
  - 0.4
  - 3.2
  uniform_dist_min:
  - -0.4
  - 2.2
  warmup: false
  warmup_iterations: 250
