predictor_name_default: 'I_love_control'
# If controller does not specify predictor_specification (leave empty)
# a predictor from "predictors:predictor_name_default" from below is loaded
# Check config.yml and config_testing.yml to learn more on how predictors are selected

predictors:
  ### THESE ARE DEFAULT PREDICTORS! DON'T CHANGE THEM, RATHER ADD YOUR PREDICTOR BELOW
  neural_default:
    predictor_type: 'neural'
    model_name: 'GRU-6IN-32H1-32H2-5OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/Tutorial/Models/'
    update_before_predicting: True
  GP_default:
    predictor_type: 'GP'
    model_name: 'SGP_10'
    path_to_model: './SI_Toolkit_ASF/Experiments/Tutorial/Models/'
  ODE_default:
    predictor_type: 'ODE'
    model_name:
    intermediate_steps: 10
  ODE_TF_default:
    predictor_type: 'ODE_TF'
    model_name:
    intermediate_steps: 4

  # ADD YOUR PREDICTORS BELOW

  I_love_control:
    predictor_type: 'neural'  # Possible options are: 'neural', 'GP', 'ODE, 'ODE_TF'
    model_name:
    path_to_model: './SI_Toolkit_ASF/Experiments/Pretrained-RNN-1/Models/'
    update_before_predicting: True

  I_love_control_too:
    predictor_type: 'ODE'
    model_name:
    intermediate_steps: 10

  Tryout:
    predictor_type: 'neural'
    model_name: 'Dense-10IN-64H1-128H2-64H3-8OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/0_tryout/Models'
    update_before_predicting: False 

  DNN:
    predictor_type: 'neural'
    model_name: 'Dense-10IN-64H1-128H2-64H3-8OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/0_DNN/Models'
    update_before_predicting: False 

  LSTM:
    predictor_type: 'neural'
    model_name: 'LSTM-10IN-16H1-32H2-16H3-8OUT-1'
    path_to_model: './SI_Toolkit_ASF/Experiments/0_LSTM/Models'
    update_before_predicting: True 

  ActiveLearning:
    predictor_type: 'neural'
    model_name: 'Custom-11IN-ODE_module.py-STModel-9OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/0_AL/Models/'
    update_before_predicting: False
