map_ext: '.png'

# map paths
map_path: 'utilities/maps_files/maps/Hockenheim'
waypoint_path: 'utilities/maps_files/waypoints/Hockenheim_wp'

# starting pose for map
starting_positions: 
 - [0., 0., -2.15]
 - [0., 0., -2.4]
