map_ext: '.png'

# map paths
map_path: 'utilities/maps_files/maps/Budapest'
waypoint_path: 'utilities/maps_files/waypoints/Budapest_wp'

# starting pose for map
starting_positions: 
 - [0., 0., -2.7] # Budapest



  