map_ext: '.png'

# map paths
map_path: 'utilities/maps_files/maps/Montreal'
waypoint_path: 'utilities/maps_files/waypoints/Montreal_wp'

# starting pose for map
starting_positions: 
 - [0., 0., 1.55]
