map_ext: '.png'

# map paths
map_path: 'utilities/maps_files/maps/Austin'
waypoint_path: 'utilities/maps_files/waypoints/Austin_wp'


# starting pose for map
starting_positions: 
 - [0., 0., 0.7] # Austin



  