map_ext: '.png'

# map paths
map_path: 'utilities/maps_files/maps/Melbourne'
waypoint_path: 'utilities/maps_files/waypoints/Melbourne_wp'

# starting pose for map
starting_positions: 
 - [0., 0., -2.6] 
