map_ext: '.png'

# map paths
map_path: 'utilities/maps_files/maps/double_s'
waypoint_path: 'utilities/maps_files/waypoints/double_s_wp'

# starting pose for map
starting_positions: 
 - [0.0, 0.0, -1.5]
  
# TODO: Set map specific controller parameters here
# TODO: Maybe also waypoint settings for interpolation