map_ext: '.png'

# map paths
map_path: 'utilities/maps_files/maps/MexicoCity'
waypoint_path: 'utilities/maps_files/waypoints/MexicoCity_wp'

# starting pose for map
starting_positions: 
 - [0., 0., 0.1]
 - [0., 0., 0.3]
