map_ext: '.png'

# map paths
map_path: 'utilities/maps_files/maps/MoscowRaceway'
waypoint_path: 'utilities/maps_files/waypoints/MoscowRaceway_wp'

# starting pose for map
starting_positions: 
 - [0., 0., -1.4] 
