map_ext: '.png'

# map paths
map_path: 'utilities/maps/hangar9/hangar9'
waypoint_path: 'utilities/maps/hangar9/hangar9_wp'

# starting pose for map
starting_positions: 
 - [0., 0., 0.75]

waypoints:
  decrease_resolution_factor: 1
  ignore_waypoints: 1